### ISSUE TITLE
CPP06/ex00

### ISSUE THREAD

**Issue by Lurik13** [DailyWind00/42-depot#1]
Si tu mets juste une lettre (ScalarConverter::convert("a");), ca marche po...

**Comment by DailyWind00** [comment]
Je suis au courrant, les correcteurs m'ont mis faux a cet exercice mais
exceptionnellement on a le droit de continuer sur le cpp 06 donc c'est
passé à 80%

Le mar. 13 août 2024, 12:00, Lucas Ribette ***@***.***> a
écrit :

**Comment by DailyWind00** [comment]
Mec quand je ferais le git pour cpp 06 tu pourras faire une issue stv

**Comment by DailyWind00** [comment]
Ça pourrait facilement être géré :
Si taille de l'input == 1:
    Tu affiches la string
